### ISSUE TITLE
Overview of Progress Bar

### ISSUE THREAD

**Issue by AlanPS** [deraadt/Moodle-block_progress#30]
how do a block with the overview?

I need some kind of overview of equal rank list for the first 5 placed on the course according to the percentage of progress.

**Comment by deraadt** [comment]
Hi, Alan.

I'm not sure I understand your question entirely. This is not the best place to have a discussion.

Feel free to look at the code to see how the Overview page is included and linked to.

If you're starting a new pluging, you might want to look at activity completion rather than copying how the Progress Bar works.
